import keyMirror from 'keymirror';

export default keyMirror({
  LARGESCREEN_DASHBOARD_CLEAR: null,
  LARGESCREEN_DASHBOARD_LOAD: null,
  LARGESCREEN_DASHBOARD_LOAD_SUCCESS: null,
  LARGESCREEN_DASHBOARD_LOAD_FAILED: null,

  LARGESCREEN_DASHBOARD_MODULES_LOAD: null,
  LARGESCREEN_DASHBOARD_MODULES_LOAD_SUCCESS: null,
  LARGESCREEN_DASHBOARD_MODULES_LOAD_FAILED: null,

  LARGESCREEN_CURRENT_MODULE_LOAD: null,
  LARGESCREEN_CURRENT_MODULE_LOAD_SUCCESS: null,
  LARGESCREEN_CURRENT_MODULE_LOAD_FAILED: null,

  LARGESCREEN_DASHBOARD_NAME_MOD: null,
  LARGESCREEN_DASHBOARD_NAME_MOD_SUCCESS: null,
  LARGESCREEN_DASHBOARD_NAME_MOD_FAILED: null,
  LARGESCREEN_DASHBOARD_NAME_MOD_PARAMS_ERROR: null,

  LARGESCREEN_CURRENT_MODULE_MOD: null,
  LARGESCREEN_CURRENT_MODULE_MOD_SUCCESS: null,
  LARGESCREEN_CURRENT_MODULE_MOD_FAILED: null,
  LARGESCREEN_CURRENT_MODULE_MOD_PARAMS_ERROR: null,

  LARGESCREEN_DASHBOARD_DEPLOY: null,
  LARGESCREEN_DASHBOARD_DEPLOY_SUCCESS: null,
  LARGESCREEN_DASHBOARD_DEPLOY_FAILED: null
});

export const LARGESCREEN_DASHBOARD_NAME_FORM = 'LARGESCREEN_DASHBOARD_NAME_FORM';
export const LARGESCREEN_COMPONENT_FORM = 'LARGESCREEN_COMPONENT_FORM';
