import keyMirror from 'keymirror';

export default keyMirror({
  DASHBOARD_LIST_LOAD: null,
  DASHBOARD_LIST_LOAD_SUCCESS: null,
  DASHBOARD_LIST_LOAD_FAILED: null,
  DASHBOARD_BASE_MOD: null,
  DASHBOARD_BASE_MOD_SUCCESS: null,
  DASHBOARD_BASE_MOD_FAILED: null,
  DASHBOARD_BASE_MOD_PARAMS_ERROR: null,

  DASHBOARD_DELETE: null,
  DASHBOARD_DELETE_SUCCESS: null,
  DASHBOARD_DELETE_FAILED: null,

  DASHBOARD_COPY: null,
  DASHBOARD_COPY_SUCCESS: null,
  DASHBOARD_COPY_FAILED: null,

  DASHBOARD_DEPLOY: null,
  DASHBOARD_DEPLOY_SUCCESS: null,
  DASHBOARD_DEPLOY_FAILED: null,

  DASHBOARD_DOWNLOAD: null,
  DASHBOARD_DOWNLOAD_SUCCESS: null,
  DASHBOARD_DOWNLOAD_FAILED: null,

  DASHBOARD_USERMODE_SET: null,
  DASHBOARD_EXPORT_MODAL_SET: null,

  DASHBOARD_TEMPLATES_LOAD: null,
  DASHBOARD_TEMPLATES_LOAD_SUCCESS: null,
  DASHBOARD_TEMPLATES_LOAD_FAILED: null,

  DASHBOARD_DELETE_MODAL_SET: null
});

export const CREATE_DASHBOARD_FORM = 'CREATE_DASHBOARD_FORM';
